# Generated by Django 3.0 on 2021-03-19 03:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('trash', 'Trash'), ('published', 'Published')], max_length=9)),
                ('imported_t', models.DateTimeField()),
                ('url', models.URLField()),
                ('creator', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('last_modified_t', models.DateTimeField()),
                ('product_name', models.TextField(blank=True)),
                ('quantity', models.TextField(blank=True)),
                ('brands', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('labels', models.TextField(blank=True)),
                ('cities', models.TextField(blank=True)),
                ('purchase_places', models.TextField(blank=True)),
                ('stores', models.TextField(blank=True)),
                ('ingredients_text', models.TextField(blank=True)),
                ('traces', models.TextField(blank=True)),
                ('serving_size', models.TextField(blank=True)),
                ('nutriscore_score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('nutriscore_grade', models.IntegerField()),
                ('main_category', models.TextField(blank=True)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
