# Generated by Django 3.0 on 2021-03-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imported_t',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nutriscore_grade',
        ),
    ]
