# Generated by Django 3.0 on 2021-03-21 21:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsUpdateHistory',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_products', models.IntegerField(blank=True, null=True)),
                ('updated_products', models.IntegerField(blank=True, null=True)),
                ('deleted_products', models.IntegerField(blank=True, null=True)),
                ('update_t', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
