version: "3"

services:
  django-rest:
    build: ./open_food_facts/
    image: my_django
    command: python ./manage.py runserver 0.0.0.0:8000
    ports: 
    - "8000:8000"
    container_name: challenge_django_rest
    volumes: 
    - ./open_food_facts/:/usr/app